const spanishWords = [
  "AL","AR","AS","DA","DE","DI","DO","EL","EN","ES","FE","HA","HE","IR","LA","LE","LO","ME","MI","NI","NO","OS","OY","RE","SE","SI","SO","SU","TE","TI","TU","UN","VE","YA","YO",
  "ALA","AMA","AMO","ARO","ASA","AVE","BAR","CAL","DAR","DOS","ERA","ESA","ESE","ESO","MAR","MES","MIA","MIO","OLA","OSA","PAN","PAR","PAZ","PIE","RIO","SAL","SER","SOL","SUR","TAL","TAN","TEN","TOS","UNA","UNO","USA","USA","VER","VID",
  "ABRA","ABRE","ACRE","AGUA","AIRE","ALMA","AMOR","ARCO","ARMA","ARTE","AZUL","BALA","BESO","BOTA","CADA","CAJA","CALA","CALA","CALOR","CAMA","CAMPO","CANTO","CARTA","CASA","CASAS","CLAVE","COLOR","COMER","COPA","CORO","CREA","CUADRO","CUIDA","DADO","DAMA","DATO","DIA","DIAS","DICE","DIGO","DIOS","DONA","DORA","ECO","EDAD","EJE","ELLA","ELLO","ENTRA","ERES","ESTA","ESTE","FLOR","FOCO","FOTO","FUEGO","GATO","GIRA","GIRO","GOL","GOTA","GRANO","GRIS","HILO","HORA","HOJA","HUMO","IDEA","ISLA","JUEGO","LADO","LANA","LARGO","LATA","LAVA","LENTO","LIMON","LISTA","LLAVE","LUGAR","LUNA","LUNAS","LUZ","MALO","MANO","MAPA","MARCO","MASA","MATE","MESA","MESAS","METAL","MIEL","MIRA","MODA","MODO","MOLAR","MONTE","MUNDO","MURAL","MUSEO","MUSICA","NADA","NARIZ","NEGRO","NETO","NIDO","NIÑA","NIÑO","NIVEL","NOCHE","NORTE","NOTA","NUBE","NUBES","NUDO","OESTE","OLA","OLAS","OLIVO","ORO","OSO","OTOÑO","PACTO","PADRE","PAISAJE","PALMA","PANEL","PANES","PARED","PARTE","PASO","PAZ","PECHO","PERA","PERRO","PIANO","PIEDRA","PISO","PLANO","PLATA","PLAZA","POCO","PODER","POEMA","POLVO","PUENTE","PUERTA","PUNTO","RAMA","RATA","RATON","RAYO","REAL","RETO","RICO","RISA","RITMO","ROCA","ROJO","RONDA","ROPA","ROSA","RUTA","SABER","SABOR","SALA","SALON","SALTO","SANGRE","SECO","SEDA","SELLO","SEÑAL","SIEMPRE","SILLA","SITIO","SOBRA","SOLAR","SONIDO","SUELO","SUENO","TARDE","TECHO","TELA","TEMOR","TENOR","TIERRA","TIMBRE","TINTA","TOCAR","TORRE","TRAMA","TRATO","TRES","TRIGO","TURNO","UNICO","UNIDO","UNIR","VASO","VELA","VENTA","VERDE","VIA","VIDA","VIDAS","VIENTO","VIGOR","VISOR","VISTA","VOTO","YEMA",
  "AMIGO","ARBOL","ARENA","BLANCO","BRISA","CABRA","CALLE","CAMINO","CANAL","CARNE","CLARO","CREAR","DULCE","FIRME","HOGAR","JOVEN","LIBRO","MANCHA","MANGO","MANTO","MAYOR","MENTA","MONTES","MORAL","MOVER","NOBLE","NOMBRE","NUBES","PASAR","PISTA","RUMBO","SABIO","SALIR","TEMPO","TENER","TESORO","TEXTO","VACIO","VALOR","VENTAS","VISITA",
  "ABRIR","ARROZ","CAMINO","CANCION","COMETA","COMIDA","CUENTO","DENTRO","ESPINA","ESTADO","FIGURA","FUERZA","JARDIN","MONTES","NACION","OBJETO","PASADO","PIEDRA","PLANETA","PUEBLO","SEMANA","SONRISA","TIEMPO","VENTANA",
]

function normalizeSpanishWord(word: string) {
  return word
    .trim()
    .toUpperCase()
    .replace(/Ñ/g, "__ENYE__")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/__ENYE__/g, "Ñ")
}

export const SPANISH_VALID_WORDS = new Set(
  spanishWords
    .map(normalizeSpanishWord)
    .filter((word) => word.length >= 2 && word.length <= 15)
)
